// Generated by CoffeeScript 1.7.1
(function() {
  App.prepareArrayfromCSV = function(csvstring) {
    var resArray;
    resArray = CSVToArray(csvstring, " ");
    console.log(resArray);
    return resArray;
  };

  App.prepareArrayfromCSV("1 2 3 4 5 \n # 3 4 5 6 7 \n # e f e m b z d");

}).call(this);
