// Generated by CoffeeScript 2.7.0
(function() {
  // Parsing URDF to robot model shown on website
  // ====================================
  // Function in this file prepares robot in App namespace from xml string ( URDF file)
  window.parseRobot = function(xml) {
    var error, robot, robotBaseMaterial, xmelon;
    try {
      xmelon = $.parseXML(xml); // enabling use of jQuery functions
    } catch (error1) {
      error = error1;
      console.log(error);
      return false;
    }
    if (window.robotmaterialcollection != null) {
      window.robotmaterialcollection.reset();
    } else {
      window.robotmaterialcollection = new App.RobotMaterialCollection();
    }
    if (window.robotlinkcollection != null) {
      window.robotlinkcollection.reset();
    } else {
      window.robotlinkcollection = new App.RobotLinkCollection();
    }
    if (window.robotjointcollection != null) {
      window.robotjointcollection.reset();
    } else {
      window.robotjointcollection = new App.RobotJointCollection();
    }
    //window.robotlinkcollection=new App.RobotLinkCollection();

    // Using jQery parseXML function, as return we get JQery parsable XML document
    xmelon = $.parseXML(xml);
    robotBaseMaterial = new THREE.MeshPhongMaterial({
      color: 0x6E23BB,
      specular: 0x6E23BB,
      shininess: 50
    });
    window.robot = new THREE.Object3D();
    window.robot.name = "robot";
    $(xmelon).find("color").parent().each(function(index) {
      var robotcolor;
      robotcolor = new App.RobotMaterial($.xml2json(this));
      window.robotmaterialcollection.add(robotcolor);
      return true;
    });
    // We are creating robotlink objects, from their description.
    // Link is a part as defined in URDF i.e. it is description of a part that is rigid body with such features as intertia, visual etc

    // Steps to do that:

    // 1. finding adequate parts by jquery
    // 2. translating them from xml to json
    // 3. adding ( hacking ??) to them reference to materialcollection (so that they can access colors)
    // 4. making robotlink object from the json description
    // 5. adding it to collection (robotlinkcollection)
    // 6. adding 3D THREE object to robot
    $(xmelon).find("link").each(function(index) {
      var robotlink, tjson;
      tjson = $.xml2json(this);
      tjson["materialcollection"] = window.robotmaterialcollection;
      robotlink = new App.RobotLink(tjson);
      window.robotlinkcollection.add(robotlink);
      window.robot.add(robotlink.get("link"));
      return true;
    });
    $(xmelon).find("joint").each(function(index) {
      var robotjoint;
      robotjoint = new App.RobotJoint($.xml2json(this));
      robotjoint.set("linkcollection", window.robotlinkcollection);
      return window.robotjointcollection.add(robotjoint);
    });
    robot = window.robot;
    return robot;
  };

}).call(this);
