// Generated by CoffeeScript 1.6.2
(function() {
  var Joint, Link, Visualprop, urdf2model;

  urdf2model = function(urdf) {
    return urdf;
  };

  Link = (function() {
    function Link() {}

    Link.prototype.name = "fufu";

    Link.visual;

    return Link;

  })();

  Visualprop = (function() {
    function Visualprop() {}

    Visualprop.prototype.geometry = Visualprop.makegeometry(shape, args);

    Visualprop.prototype.makegeometry = function(shape, args) {
      return geometry;
    };

    Visualprop.prototype.makebox = function(size) {
      return box;
    };

    Visualprop.prototype.makesphere = function(radius) {
      return sphere;
    };

    Visualprop.prototype.makecylinder = function(radius, lenght) {
      return cylinder;
    };

    return Visualprop;

  })();

  Joint = (function() {
    function Joint() {}

    Joint.prototype.type = "fufu";

    Joint.prototype.name = "costam";

    Joint.prototype.origin = [1, 2, 3];

    return Joint;

  })();

}).call(this);
